CANDLES_DATA_PATH = "data/candles"
DOWNLOAD_CANDLES_CONFIG_YML = "ultraboost_files/scripts_configs/data_downloader_config.yml"
BOTS_FOLDER = "ultraboost_files/bots"
CONTROLLERS_PATH = "quants_lab/controllers"
CONTROLLERS_CONFIG_PATH = "ultraboost_files/controller_configs"
OPTIMIZATIONS_PATH = "quants_lab/optimizations"
ULTRABOOST_TEMPLATES = "ultraboost_files/templates"