[theme]
base="dark"
primaryColor="#FF8C00"
backgroundColor="#0e1117"
secondaryBackgroundColor="#1a1a2e"
textColor="#fafafa"
font="monospace"
[server]
maxUploadSize = 700
headless = true
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
